name_info_dict1 = {u'name_raw_contact_id': u'155', u'display_name_source': u'40', u'contact_id': u'155', u'is_super_primary': u'0', u'account_name': u'yogesh.kamble102@gmail.com', u'sourceid': u'2aa05a418f966ebb', u'display_name': u'Arvind', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Arvind', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'925i2aa05a418f966ebb.0r479-2D4F573D4733', u'raw_contact_id': u'155', u'data4': u'748866188919+', u'is_sim': u'0', u'data1': u'+919881668847', u'data2': u'2', u'account_type': u'com.google', u'sort_key': u'Arvind', u'in_visible_group': u'1', u'display_name_alt': u'Arvind', u'link_type1': u'com.google', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'data_sync4': u'1', u'is_primary': u'0', u'raw_contact_linkpriority1': u'155', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Arvind', u'dirty': u'0', u'starred': u'0', u'_id': u'920', u'phonetic_name_style': u'3'}

name_info_dict2 = {u'name_raw_contact_id': u'155', u'display_name_source': u'40', u'contact_id': u'155', u'is_super_primary': u'0', u'account_name': u'vnd.sec.contact.phone', u'display_name': u'Arvind', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Arvind', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'925i2aa05a418f966ebb.0r479-2D4F573D4733', u'raw_contact_id': u'479', u'data4': u'748866188919+', u'is_sim': u'0', u'data1': u'+919881668847', u'data2': u'2', u'account_type': u'vnd.sec.contact.phone', u'sort_key': u'Arvind', u'in_visible_group': u'1', u'display_name_alt': u'Arvind', u'link_type1': u'com.google', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'is_primary': u'0', u'raw_contact_linkpriority1': u'155', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Arvind', u'dirty': u'1', u'starred': u'0', u'_id': u'2817', u'phonetic_name_style': u'3'}

#Duplicate Names
name_info_dict3 = {u'name_raw_contact_id': u'139', u'display_name_source': u'40', u'contact_id': u'862', u'is_super_primary': u'0', u'account_name': u'yogesh.kamble102@gmail.com', u'sourceid': u'540121ee0c7575ef', u'display_name': u'Abhijit', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Abhijit', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'925i540121ee0c7575ef', u'raw_contact_id': u'139', u'data4': u'702522411219+', u'is_sim': u'0', u'data1': u'+912114225207', u'data2': u'1', u'account_type': u'com.google', u'sort_key': u'Abhijit', u'in_visible_group': u'1', u'display_name_alt': u'Abhijit', u'link_type1': u'com.google', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'data_sync4': u'1', u'is_primary': u'0', u'raw_contact_linkpriority1': u'139', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Abhijit', u'dirty': u'0', u'starred': u'0', u'_id': u'802', u'phonetic_name_style': u'3'}

name_info_dict4 =  {u'name_raw_contact_id': u'463', u'display_name_source': u'40', u'contact_id': u'861', u'is_super_primary': u'0', u'account_name': u'vnd.sec.contact.phone', u'display_name': u'Abhijit', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Abhijit', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'0r463-2D2F3B3D3F3D53', u'raw_contact_id': u'463', u'data4': u'702522411219+', u'is_sim': u'0', u'data1': u'+912114225207', u'data2': u'1', u'account_type': u'vnd.sec.contact.phone', u'sort_key': u'Abhijit', u'in_visible_group': u'1', u'display_name_alt': u'Abhijit', u'link_type1': u'vnd.sec.contact.phone', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'is_primary': u'0', u'raw_contact_linkpriority1': u'463', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Abhijit', u'dirty': u'1', u'starred': u'0', u'_id': u'2779', u'phonetic_name_style': u'3'}

name_info_dict5 = {u'name_raw_contact_id': u'139', u'display_name_source': u'40', u'contact_id': u'862', u'is_super_primary': u'0', u'account_name': u'yogesh.kamble102@gmail.com', u'sourceid': u'540121ee0c7575ef', u'display_name': u'Abhijit', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Abhijit', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'925i540121ee0c7575ef', u'raw_contact_id': u'139', u'data4': u'675306579919+', u'is_sim': u'0', u'data1': u'+919975603576', u'data2': u'2', u'account_type': u'com.google', u'sort_key': u'Abhijit', u'in_visible_group': u'1', u'display_name_alt': u'Abhijit', u'link_type1': u'com.google', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'data_sync4': u'1', u'is_primary': u'0', u'raw_contact_linkpriority1': u'139', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Abhijit', u'dirty': u'0', u'starred': u'0', u'_id': u'801', u'phonetic_name_style': u'3'}

name_info_dict6 = {u'name_raw_contact_id': u'463', u'display_name_source': u'40', u'contact_id': u'861', u'is_super_primary': u'0', u'account_name': u'vnd.sec.contact.phone', u'display_name': u'Abhijit', u'data_version': u'0', u'last_time_contacted': u'0', u'sort_key_alt': u'Abhijit', u'send_to_voicemail': u'0', u'version': u'2', u'lookup': u'0r463-2D2F3B3D3F3D53', u'raw_contact_id': u'463', u'data4': u'675306579919+', u'is_sim': u'0', u'data1': u'+919975603576', u'data2': u'2', u'account_type': u'vnd.sec.contact.phone', u'sort_key': u'Abhijit', u'in_visible_group': u'1', u'display_name_alt': u'Abhijit', u'link_type1': u'vnd.sec.contact.phone', u'mimetype': u'vnd.android.cursor.item/phone_v2', u'is_primary': u'0', u'raw_contact_linkpriority1': u'463', u'times_contacted': u'0', u'name_verified': u'0', u'display_name_reverse': u'Abhijit', u'dirty': u'1', u'starred': u'0', u'_id': u'2778', u'phonetic_name_style': u'3'}
